# Generated by Django 6.0.2 on 2026-02-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handicraftapp', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
